Repository Hack-Your-Future-Group-A-Dream-Team/iSchool, pull requests merged in 2021-01, with the labels that each got.

#44 landing-page
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/Home.jsx
  client/src/Login.jsx
  client/src/Secret.jsx
  client/src/components/Button.css
  client/src/components/Button.js
  client/src/components/Footer.css
  client/src/components/Footer.js
  client/src/components/LandingSec.css
  client/src/components/LandingSec.js
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  client/src/components/pages/Home.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  client/src/setupTests.js
  client/src/withAuth.jsx
Labels: front-end landing page

#58 Validation email
  .env
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Context/AuthContext.js
  client/src/Services/AuthService.js
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  client/src/components/pages/Activate.js
  client/src/components/pages/EditProfile.js
  client/src/components/pages/Login.css
  client/src/components/pages/Login.js
  client/src/components/pages/Register.js
  index.js
  package-lock.json
  package.json
  routes/User.js
Labels: Back-end, Front-end

#60 Info page
  client/package-lock.json
  client/public/index.html
  client/public/logo 2.png
  client/public/working logo 2.png
  client/src/App.js
  client/src/components/Info.css
  client/src/components/Info.js
  client/src/components/LandingSec.js
  client/src/components/Navbar.js
  client/src/components/assets/Landing page background.jpg
  client/src/components/assets/Reception.jpg
  client/src/components/assets/education.jpg
  client/src/components/assets/networks.jpg
  client/src/components/assets/secondary.jpg
  client/src/components/assets/student.jpg
  client/src/components/assets/students.jpg~merged
  client/src/components/pages/Info.js
  index.js
  package-lock.json
Labels: front-end info page

#61 Reset password
  .env
  client/package-lock.json
  client/src/App.js
  client/src/Services/AuthService.js
  client/src/components/Button.js
  client/src/components/Footer.css
  client/src/components/Footer.js
  client/src/components/LandingSec.css
  client/src/components/LandingSec.js
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  client/src/components/assets/cover.jpg
  client/src/components/assets/students.jpg~merged
  client/src/components/pages/Activate.js
  client/src/components/pages/ForgotPassword.js
  client/src/components/pages/Login.css
  client/src/components/pages/Login.js
  client/src/components/pages/MySchools.js
  client/src/components/pages/Register.js
  client/src/components/pages/ResetPassword.js
  helpers/dbErrorHandler.js
  models/User.js
  package-lock.json
  passport.js
  routes/User.js
Labels: Back-end, Front-end

#73 Autocomplete and search schools
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/getSchools.css
  client/src/components/getSchools.js
  client/src/components/searchBar.css
  client/src/components/searchBar.js
Labels: Front-end

#74 Complete filter component with radio buttons
  .DS_Store
  .env
  client/src/components/filterSchool.css
  client/src/components/filterSchool.js
  client/src/components/getSchools.js
  client/src/components/pages/SearchSchool.js
  routes/schools.js
Labels: Front-end, search school

#79 Google sign in
  .env
  client/package-lock.json
  client/package.json
  client/src/components/pages/Activate.js
  client/src/components/pages/ForgotPassword.js
  client/src/components/pages/Login.css
  client/src/components/pages/Login.js
  client/src/components/pages/Register.js
  client/src/components/pages/ResetPassword.js
  models/User.js
  package-lock.json
  package.json
  routes/User.js
Labels: Back-end, Front-end

#72 Change sign up
  client/src/components/LandingSec.css
  client/src/components/LandingSec.js
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  client/src/components/pages/Activate.js
  client/src/components/pages/ForgotPassword.js
  client/src/components/pages/Login.css
  client/src/components/pages/Login.js
  client/src/components/pages/Register.js
  client/src/components/pages/ResetPassword.js
  models/User.js
  routes/User.js
Labels: Back-end, Front-end

#82 Give review functionality
  client/src/components/getSchools.css
  client/src/components/getSchools.js
  controllers/interaction_controller.js
Labels: Front-end, search school

#83 Add and remove favorite school
  client/src/components/getSchools.js
  client/src/components/myschool.js
  client/src/components/pages/MySchools.js
  controllers/favorites.js
  models/User.js
  routes/favorites.js
Labels: Back-end, Front-end

#80 Resize image
  client/src/App.js
  client/src/components/Info.css
  client/src/components/LandingSec.css
  client/src/components/LandingSec.js
  client/src/components/Navbar.css
  client/src/components/pages/MySchools.js
Labels: resize image

#87 Comments front
  .vscode/settings.json
  client/src/components/Comment/CommentInput.js
  client/src/components/Comment/CommentInputError.js
  client/src/components/Comment/CommentRecord.css
  client/src/components/Comment/CommentRecord.js
  client/src/components/Comment/CommentSendSuccess.js
  client/src/components/Comment/CommentsList.js
  client/src/components/Comment/utils/pushCommentToDB.js
  client/src/components/SchoolBlock.js
  client/src/components/getSchools.css
  client/src/components/getSchools.js
  controllers/interaction_controller.js
  models/School.js
Labels: Front-end

#99 fixing in calculations and layout
  client/src/components/Comment/CommentInput.js
  client/src/components/Comment/CommentRecord.css
  client/src/components/Comment/CommentRecord.js
  client/src/components/Comment/CommentsList.js
  client/src/components/LandingSec.css
  client/src/components/Navbar.js
  client/src/components/SchoolBlock.js
  client/src/components/getSchools.js
  controllers/interaction_controller.js
Labels: Front-end
